switch.activity_room_ac:
  friendly_name: 活动室空调
switch.activity_room_light:
  friendly_name: 活动室灯
switch.bar_light:
  friendly_name: 吧台灯
switch.bathroom_fan:
  friendly_name: 洗手间风扇
switch.bathroom_light:
  friendly_name: 洗手间灯
switch.bedroom_ac:
  friendly_name: 卧室暖气
switch.kitchen_light:
  friendly_name: 厨房灯
switch.front_door_light:
  friendly_name: 前门灯
switch.living_room_light:
  friendly_name: 起居室灯
sun.sun:
  friendly_name: 太阳
remote.harmony_hub:
  friendly_name: 遥控器
sensor.yr_symbol:
  friendly_name: 天气
